# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/boto3',
                'doc_host': 'https://bchapm5.github.io',
                'git_url': 'https://github.com/bchapm5/boto3',
                'lib_path': 'boto3'},
  'syms': {'boto3.core': {'boto3.core.foo': ('core.html#foo', 'boto3/core.py')}}}